spring:
    datasource:
      url: jdbc:mysql://192.168.154.129:3306/springbootdemo?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

    # REDIS (RedisProperties)
    redis:
      # Redis数据库索引（默认为0）
      database: 0
      host: 192.168.154.129
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 0
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0


#暴露所有端口
management:
  security:
    enabled: false