spring:
    profiles:
      # 多个之间用逗号分隔
      active: dev

    datasource:
      driver-class-name: com.mysql.jdbc.Driver

      druid:
        stat-view-servlet:
          login-username: mytest
          login-password: 123456
        initial-size: 5
        min-idle: 10
        max-active: 20

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5

    mail:
      host: smtp.126.com
      username: liyftest@126.com
      password: justtest1
